framework:
  messenger:
    failure_transport: failed
    transports:
      # https://symfony.com/doc/current/messenger.html#transport-configuration
      async:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        retry_strategy:
          # milliseconds delay, 30 seconds
          delay: 30000
      failed: '%env(MESSENGER_TRANSPORT_DSN)%?queue_name=failed'

    routing:
       # Route your messages to the transports
       'App\Message\CourseIndexRequest': async
       'App\Message\UserIndexRequest': async
       'App\Message\MeshDescriptorIndexRequest': async
       'App\Message\LearningMaterialIndexRequest': async
       'App\Message\LearningMaterialTextExtractionRequest': async
       'App\Message\CourseDeleteRequest': async
       'App\Message\SessionDeleteRequest': async
       'App\Message\LearningMaterialDeleteRequest': async

    default_bus: messenger.bus.default
    buses:
      messenger.bus.default:
        middleware:
          # each time a message is handled, the Doctrine connection
          # is "pinged" and reconnected if it's closed.
          - doctrine_ping_connection
          # After handling, the Doctrine connection is closed
          - doctrine_close_connection

when@test:
   framework:
       messenger:
           transports:
               # replace with your transport name here (e.g., my_transport: 'in-memory://')
               # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
               async: 'in-memory://'
               failed: 'in-memory://'
